# Generated by Django 2.1.2 on 2018-12-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
