# Generated by Django 2.1.2 on 2018-12-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='costo_P',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lista',
            name='costo_R',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lista',
            name='total_A',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lista',
            name='total_C',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costoP',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costoR',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='notas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
