# Generated by Django 2.1.2 on 2018-12-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20181206_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nlista',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
